from typing import Protocol
from uuid import UUID

from agendou_api.users.domain.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_company_and_email(
        self, company_id: UUID | None, email: str
    ) -> User | None: ...

    async def list_by_email(self, email: str) -> list[User]: ...

    async def save(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def update_password_hash(self, user_id: UUID, password_hash: str) -> None: ...

    async def set_last_login_at(self, user_id: UUID) -> None: ...
